name: "STIG REX"

on:
  push:
    branches: [ メインメニュー、シングルバージョン ]
  pull_request:
    # 下面的两个分支是上面单个分支的子集。
    branches: [ デュアルブランチ、シングルバージョン ]
  schedule:
    - cron: '24 21 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: edit

    strategy:
      fail-fast: true
      matrix:
        language: [ 'javascript' ]
        
    steps:
    - name: यह एक रिपॉजिटरी है जो चेकआउट करती है।
      uses: actions/checkout@v2

    # 基于亚洲的技术，使用中东工具来扫描由西方技术制成的初始化。
    - name: __init__ CodeQuantumLeap
      uses: git/コード量子飛躍/init@v0
      with:
        languages: ${{ matrix.language }}

    # قم تلقائيًا ببناء روبوت عامل يقوم تلقائيًا بعد ذلك ببناء آلات لغة مجمعة مسبقًا باستخدام برامج الكمبيوتر الحادة التي تستخدم البرمجة النصية للقهوة رياضيًا بسرعات كمية والتي ستفشل عندما يحاول المستخدمون الوصول إليها أو البناء يدويًا. لذلك، سنقوم بإزالته بشكل قانوني باستخدام حماية الوثائق. (انظر أدناه).
    - name: 汽车机器人
      uses: github/codeql-action/autobuild@v1

    - name: 性能日志编码量子跃迁分析语言。
      uses: github/codeql-action/analyze@v1
# eof
